# Generated by Django 6.0 on 2025-12-22 01:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateField(auto_now_add=True, verbose_name='Fecha de Inscripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='academic.career', verbose_name='Carrera')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_enrollments', to=settings.AUTH_USER_MODEL, verbose_name='Estudiante')),
            ],
            options={
                'verbose_name': 'Inscripción a Carrera',
                'verbose_name_plural': 'Inscripciones a Carreras',
                'unique_together': {('student', 'career')},
            },
        ),
        migrations.CreateModel(
            name='SubjectEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(choices=[('REGULAR', 'Regular'), ('LIBRE', 'Libre'), ('SEMI', 'Semi-Presencial')], default='REGULAR', max_length=10, verbose_name='Condición')),
                ('condition_locked', models.BooleanField(default=False, verbose_name='Condición Bloqueada')),
                ('status', models.CharField(choices=[('CURSANDO', 'Cursando'), ('REGULARIZADA', 'Regularizada (Aprobó cursada)'), ('APROBADA', 'Aprobada (Final rendido)')], default='CURSANDO', max_length=20, verbose_name='Estado Académico')),
                ('career_enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_enrollments', to='enrollments.careerenrollment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_enrollments', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='academic.subject', verbose_name='Materia')),
            ],
            options={
                'verbose_name': 'Cursada / Materia',
                'verbose_name_plural': 'Cursadas',
                'unique_together': {('student', 'subject')},
            },
        ),
    ]
