# Generated by Django 6.0 on 2025-12-22 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='documentation',
            field=models.FileField(blank=True, null=True, upload_to='documentacion/%Y/%m/', verbose_name='Documentación (PDF/Img)'),
        ),
    ]
