# Generated by Django 6.0 on 2025-12-23 13:38

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userdocument'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='documentation',
        ),
        migrations.RemoveField(
            model_name='user',
            name='requires_approval',
        ),
        migrations.AlterField(
            model_name='user',
            name='dni',
            field=models.CharField(max_length=20, unique=True, verbose_name='DNI / Pasaporte'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrativo'), ('TEACHER', 'Docente'), ('STUDENT', 'Estudiante')], default='STUDENT', max_length=50),
        ),
        migrations.AlterField(
            model_name='userdocument',
            name='file',
            field=models.FileField(upload_to=apps.users.models.user_directory_path, verbose_name='Archivo'),
        ),
    ]
