# Generated by Django 6.0 on 2025-12-22 00:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre de la Carrera')),
                ('short_name', models.CharField(max_length=50, verbose_name='Abreviatura')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
            ],
            options={
                'verbose_name': 'Carrera',
                'verbose_name_plural': 'Carreras',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre de la Materia')),
                ('year_level', models.IntegerField(choices=[(1, '1er Año'), (2, '2do Año'), (3, '3er Año')], verbose_name='Año de Cursada')),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='academic.career', verbose_name='Carrera')),
            ],
            options={
                'verbose_name': 'Materia',
                'verbose_name_plural': 'Materias',
                'ordering': ['career', 'year_level', 'name'],
            },
        ),
    ]
