# Generated by Django 6.0 on 2025-12-22 01:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Fecha del Examen')),
                ('inscription_deadline_days', models.PositiveIntegerField(default=10, verbose_name='Días de cierre antes del examen')),
                ('state', models.CharField(choices=[('OPEN', 'Abierta (Inscripciones)'), ('CLOSED_INSCRIPTION', 'Inscripción Cerrada'), ('IN_EVALUATION', 'En Evaluación (Docente confirma modalidades)'), ('GRADING', 'Evaluando (Carga de Notas)'), ('FINALIZED', 'Acta Cerrada')], default='OPEN', max_length=20, verbose_name='Estado de la Mesa')),
                ('examiners', models.ManyToManyField(limit_choices_to={'role__in': ['TEACHER', 'CAREER_HEAD']}, to=settings.AUTH_USER_MODEL, verbose_name='Tribunal Docente')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.subject', verbose_name='Materia')),
            ],
            options={
                'verbose_name': 'Mesa de Examen',
                'verbose_name_plural': 'Mesas de Examen',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ExamEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modality', models.CharField(choices=[('REGULAR', 'Regular'), ('LIBRE', 'Libre')], default='REGULAR', max_length=20, verbose_name='Modalidad Confirmada')),
                ('is_confirmed_by_teacher', models.BooleanField(default=False, verbose_name='Confirmado por Docente')),
                ('grade', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Nota Final')),
                ('absent', models.BooleanField(default=False, verbose_name='Ausente')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_enrollments', to=settings.AUTH_USER_MODEL, verbose_name='Estudiante')),
                ('exam_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='exams.examsession', verbose_name='Mesa de Examen')),
            ],
            options={
                'verbose_name': 'Inscripción a Examen',
                'verbose_name_plural': 'Inscripciones a Exámenes',
                'unique_together': {('exam_session', 'student')},
            },
        ),
    ]
