# Generated by Django 6.0 on 2026-01-22 14:35

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examsession',
            options={'ordering': ['date'], 'verbose_name': 'Mesa de Examen', 'verbose_name_plural': 'Mesas de Examen'},
        ),
        migrations.AddField(
            model_name='examenrollment',
            name='date_enrolled',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de Inscripción'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='examenrollment',
            name='is_confirmed_by_teacher',
            field=models.BooleanField(default=False, verbose_name='Confirmado'),
        ),
        migrations.AlterField(
            model_name='examenrollment',
            name='modality',
            field=models.CharField(choices=[('REGULAR', 'Regular'), ('LIBRE', 'Libre')], default='REGULAR', max_length=20, verbose_name='Modalidad'),
        ),
        migrations.AlterField(
            model_name='examsession',
            name='date',
            field=models.DateTimeField(verbose_name='Fecha y Hora del Examen'),
        ),
        migrations.AlterField(
            model_name='examsession',
            name='examiners',
            field=models.ManyToManyField(limit_choices_to={'role__in': ['TEACHER', 'CAREER_HEAD', 'ADMIN']}, to=settings.AUTH_USER_MODEL, verbose_name='Tribunal Docente'),
        ),
        migrations.AlterField(
            model_name='examsession',
            name='inscription_deadline_days',
            field=models.PositiveIntegerField(default=2, verbose_name='Días de cierre antes del examen'),
        ),
        migrations.AlterField(
            model_name='examsession',
            name='state',
            field=models.CharField(choices=[('OPEN', 'Abierta (Inscripciones)'), ('CLOSED_INSCRIPTION', 'Inscripción Cerrada'), ('IN_EVALUATION', 'En Evaluación'), ('GRADING', 'Cargando Notas'), ('FINALIZED', 'Acta Cerrada')], default='OPEN', max_length=20, verbose_name='Estado de la Mesa'),
        ),
    ]
